/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LifeGaugePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/data.ts
var DEFAULT_STATS = [
  {
    id: "stamina",
    name: "Stamina",
    icon: "\u{1F4AA}",
    currentXp: 0,
    level: 1,
    color: "#4dff88",
    baseXp: 100,
    xpIncrement: 50
  },
  {
    id: "strength",
    name: "Strength",
    icon: "\u{1F9E0}",
    currentXp: 0,
    level: 1,
    color: "#ffaa4d",
    baseXp: 100,
    xpIncrement: 50
  },
  {
    id: "knowledge",
    name: "Knowledge",
    icon: "\u{1F4DA}",
    currentXp: 0,
    level: 1,
    color: "#4da6ff",
    baseXp: 100,
    xpIncrement: 50
  }
];
var DEFAULT_TITLES = [
  {
    threshold: 0,
    name: "K\u1EBB l\u1EA1c l\xF5ng",
    icon: "\u2694\uFE0F",
    description: "B\u1EA1n lu\xF4n c\u1EA3m th\u1EA5y m\xECnh k\xE9m c\u1ECFi v\xE0 b\u1ECB b\u1ECF l\u1EA1i. B\u1EA1n th\u1EA5t b\u1EA1i trong h\u1EA7u h\u1EBFt m\u1ECDi vi\u1EC7c v\xE0 b\u1EA1n nghi ng\u1EDD kh\u1EA3 n\u0103ng c\u1EE7a b\u1EA3n th\xE2n. \u0110\u1EEBng t\u1EEB b\u1ECF, h\xE3y ti\u1EBFp t\u1EE5c c\u1ED1 g\u1EAFng!"
  },
  {
    threshold: 300,
    name: "Ng\u01B0\u1EDDi l\u1EEF kh\xE1ch",
    icon: "\u{1F6B6}",
    description: "B\u1EA1n \u0111\xE3 b\u1EAFt \u0111\u1EA7u t\xECm th\u1EA5y h\u01B0\u1EDBng \u0111i. Nh\u1EEFng b\u01B0\u1EDBc ch\xE2n \u0111\u1EA7u ti\xEAn lu\xF4n kh\xF3 kh\u0103n, nh\u01B0ng m\u1ED7i ng\xE0y b\u1EA1n l\u1EA1i v\u1EEFng v\xE0ng h\u01A1n."
  },
  {
    threshold: 800,
    name: "K\u1EBB th\u1EE9c t\u1EC9nh",
    icon: "\u{1F525}",
    description: "M\u1ED9t ng\u1ECDn l\u1EEDa nh\u1ECF \u0111\xE3 b\xF9ng ch\xE1y trong b\u1EA1n. B\u1EA1n nh\u1EADn ra r\u1EB1ng m\xECnh c\xF3 th\u1EC3 l\xE0m \u0111\u01B0\u1EE3c nhi\u1EC1u h\u01A1n nh\u1EEFng g\xEC b\u1EA1n ngh\u0129."
  },
  {
    threshold: 1500,
    name: "Chi\u1EBFn binh ki\xEAn c\u01B0\u1EDDng",
    icon: "\u{1F6E1}\uFE0F",
    description: "Nh\u1EEFng th\u1EED th\xE1ch kh\xF4ng c\xF2n l\xE0m b\u1EA1n nao n\xFAng. B\u1EA1n \u0111\xE3 r\xE8n luy\u1EC7n \u0111\u1EE7 \u0111\u1EC3 \u0111\u1EE9ng v\u1EEFng tr\u01B0\u1EDBc gi\xF4ng b\xE3o."
  },
  {
    threshold: 3e3,
    name: "B\u1EADc th\u1EA7y",
    icon: "\u{1F451}",
    description: "K\u1EF9 n\u0103ng c\u1EE7a b\u1EA1n \u0111\xE3 tr\u1EDF th\xE0nh huy\u1EC1n tho\u1EA1i trong c\u1ED9ng \u0111\u1ED3ng c\u1EE7a ri\xEAng b\u1EA1n. Ng\u01B0\u1EDDi kh\xE1c nh\xECn v\xE0o b\u1EA1n \u0111\u1EC3 t\xECm c\u1EA3m h\u1EE9ng."
  },
  {
    threshold: 5e3,
    name: "Huy\u1EC1n tho\u1EA1i s\u1ED1ng",
    icon: "\u{1F31F}",
    description: "B\u1EA1n \u0111\xE3 v\u01B0\u1EE3t qua gi\u1EDBi h\u1EA1n c\u1EE7a con ng\u01B0\u1EDDi th\u01B0\u1EDDng. C\xE2u chuy\u1EC7n c\u1EE7a b\u1EA1n s\u1EBD \u0111\u01B0\u1EE3c k\u1EC3 l\u1EA1i qua nhi\u1EC1u th\u1EBF h\u1EC7."
  }
];
var DEFAULT_SETTINGS = {
  avatarPath: ".life-gauge/avatar.png",
  taskFilePath: "Daily/quests.md",
  stats: DEFAULT_STATS,
  titles: DEFAULT_TITLES,
  skills: [],
  completedTasks: [],
  penaltyPoint: 1,
  refreshInterval: 5
};
function calculateLevel(currentXp, baseXp, xpIncrement) {
  let level = 1;
  let xpNeeded = baseXp;
  let tempXp = currentXp;
  while (tempXp >= xpNeeded) {
    tempXp -= xpNeeded;
    level++;
    xpNeeded = baseXp + (level - 1) * xpIncrement;
  }
  return { level, remainingXp: tempXp, requiredXp: xpNeeded };
}
function getTotalXp(stats) {
  return stats.reduce((acc, stat) => acc + stat.currentXp, 0);
}
function getCurrentTitle(totalXp, titles) {
  const sortedTitles = [...titles].sort((a, b) => b.threshold - a.threshold);
  return sortedTitles.find((t) => totalXp >= t.threshold) || titles[0];
}
function getNextTitle(totalXp, titles) {
  const sortedTitles = [...titles].sort((a, b) => a.threshold - b.threshold);
  return sortedTitles.find((t) => t.threshold > totalXp) || null;
}

// src/view.ts
var import_obsidian = require("obsidian");

// src/parser.ts
function getTaskKey(task) {
  const rewardsKey = (task.rewards || []).map((r) => `${r.statId}${r.amount}`).sort().join(",");
  return `${task.text}:${rewardsKey}:${task.date || ""}:${task.time || ""}`;
}
function parseTasks(content, stats) {
  const lines = content.split("\n");
  const tasks = [];
  const taskRegex = /^\s*-\s*\[([ x])\]\s*(.+?)\s*$/;
  const rewardSectionRegex = /\(([^)]+)\)/;
  const rewardRegex = /\+([0-9]+)\s+([a-zA-Z0-9-]+)/g;
  const dateRegex = /@\{([^}]+)\}/;
  const timeRegex = /@@\{([^}]+)\}/;
  const skillRegex = /#([a-zA-Z0-9\u00C0-\u1EF9-]+)/g;
  let isArchivedSection = false;
  lines.forEach((line, index) => {
    if (line.trim().toLowerCase().startsWith("## archive")) {
      isArchivedSection = true;
      return;
    }
    const match = taskRegex.exec(line);
    if (match) {
      const isProcessed = line.trim().endsWith("(done)");
      const completed = match[1] === "x";
      let remainingText = match[2];
      const rewards = [];
      const rewardMatch = rewardSectionRegex.exec(remainingText);
      if (rewardMatch) {
        const rewardsRaw = rewardMatch[1];
        let rMatch;
        while ((rMatch = rewardRegex.exec(rewardsRaw)) !== null) {
          const amount = parseInt(rMatch[1]);
          const statName = rMatch[2].toLowerCase();
          const stat = stats.find((s) => s.name.toLowerCase() === statName || s.id.toLowerCase() === statName);
          if (stat) {
            rewards.push({ statId: stat.id, amount });
          }
        }
        remainingText = remainingText.replace(rewardSectionRegex, "").trim();
      }
      let date;
      const dMatch = dateRegex.exec(remainingText);
      if (dMatch) {
        date = dMatch[1];
        remainingText = remainingText.replace(dateRegex, "").trim();
      }
      let time;
      const tMatch = timeRegex.exec(remainingText);
      if (tMatch) {
        time = tMatch[1];
        remainingText = remainingText.replace(timeRegex, "").trim();
      }
      const skills = [];
      let sMatch;
      while ((sMatch = skillRegex.exec(remainingText)) !== null) {
        skills.push(sMatch[1].toLowerCase());
      }
      remainingText = remainingText.replace(skillRegex, "").trim();
      if (!date && !time)
        return;
      tasks.push({
        originalLine: index,
        text: remainingText,
        completed,
        rewards,
        skills,
        date,
        time,
        isArchived: isArchivedSection,
        isProcessed
      });
    }
  });
  return tasks;
}
function updateTaskInContent(content, lineIndex, completed, addDone = false) {
  const lines = content.split("\n");
  if (lineIndex >= 0 && lineIndex < lines.length) {
    if (addDone) {
      lines[lineIndex] = lines[lineIndex].replace(/\[[ x]\]/, `[x]`);
      if (!lines[lineIndex].trim().endsWith("(done)")) {
        lines[lineIndex] = lines[lineIndex].trimEnd() + " (done)";
      }
    } else {
      const char = completed ? "x" : " ";
      lines[lineIndex] = lines[lineIndex].replace(/\[[ x]\]/, `[${char}]`);
    }
  }
  return lines.join("\n");
}

// src/view.ts
var VIEW_TYPE_LIFE_GAUGE = "life-gauge-view";
var LifeGaugeView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "tasks", []);
    __publicField(this, "isUpdating", false);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_LIFE_GAUGE;
  }
  getDisplayText() {
    return "Life Gauge";
  }
  getIcon() {
    return "gamepad";
  }
  async onOpen() {
    this.update();
  }
  async update() {
    if (this.isUpdating)
      return;
    this.isUpdating = true;
    try {
      await this.loadTasks();
      const visibleTasks = this.tasks.filter((t) => !t.isArchived);
      const totalXp = getTotalXp(this.plugin.settings.stats);
      const title = getCurrentTitle(totalXp, this.plugin.settings.titles);
      const nextTitle = getNextTitle(totalXp, this.plugin.settings.titles);
      const { contentEl } = this;
      contentEl.empty();
      contentEl.addClass("life-gauge-dashboard");
      this.renderHeader(contentEl, title, nextTitle, totalXp);
      this.renderStats(contentEl);
      if (this.plugin.settings.skills.length > 0) {
        this.renderSkills(contentEl);
      }
      this.renderQuests(contentEl, visibleTasks);
    } catch (e) {
      console.error("Life Gauge: Update failed", e);
    } finally {
      this.isUpdating = false;
    }
  }
  async loadTasks() {
    const file = this.app.vault.getAbstractFileByPath(this.plugin.settings.taskFilePath);
    if (file instanceof import_obsidian.TFile) {
      const content = await this.app.vault.read(file);
      this.tasks = parseTasks(content, this.plugin.settings.stats);
    } else {
      this.tasks = [];
    }
  }
  renderHeader(parent, title, nextTitle, totalXp) {
    const header = parent.createEl("div", { cls: "lg-header" });
    const avatarContainer = header.createEl("div", { cls: "lg-avatar-container" });
    const avatar = avatarContainer.createEl("img", {
      cls: "lg-avatar",
      attr: { src: this.app.vault.adapter.getResourcePath(this.plugin.settings.avatarPath) }
    });
    const info = header.createEl("div", { cls: "lg-info" });
    info.createEl("div", { cls: "lg-nickname", text: `${title.icon} ${title.name.toUpperCase()} ${title.icon}` });
    info.createEl("div", { cls: "lg-description", text: title.description });
    if (nextTitle) {
      const neededForNext = nextTitle.threshold - totalXp;
      info.createEl("div", { cls: "lg-next-rank", text: `\u{1F51C} ${neededForNext} XP \u0111\u1EC3 tr\u1EDF th\xE0nh ${nextTitle.name}` });
    } else {
      info.createEl("div", { cls: "lg-next-rank", text: `\u{1F3C6} B\u1EA1n \u0111\xE3 \u0111\u1EA1t \u0111\u1EC9nh vinh quang!` });
    }
    const settingsIcon = header.createEl("div", { cls: "lg-settings-icon", text: "\u2699\uFE0F" });
    settingsIcon.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById(this.plugin.manifest.id);
    });
  }
  renderStats(parent) {
    const statsContainer = parent.createEl("div", { cls: "lg-stats-container" });
    this.plugin.settings.stats.forEach((stat) => this.renderProgressBar(statsContainer, stat));
  }
  renderSkills(parent) {
    parent.createEl("h3", { text: "Your skills", cls: "lg-section-title" });
    const skillsGrid = parent.createEl("div", { cls: "lg-skills-grid" });
    this.plugin.settings.skills.forEach((skill) => this.renderSkillCard(skillsGrid, skill));
  }
  renderSkillCard(parent, skill) {
    const card = parent.createEl("div", { cls: "lg-skill-card" });
    const { level, remainingXp, requiredXp } = calculateLevel(skill.currentXp, skill.baseXp, skill.xpIncrement);
    const percent = Math.min(100, remainingXp / requiredXp * 100);
    card.createEl("span", { text: `${skill.icon} ${skill.name}`, cls: "lg-stat-label" });
    const barContainer = card.createEl("div", { cls: "lg-bar-container" });
    const bar = barContainer.createEl("div", { cls: "lg-bar-fill" });
    bar.style.width = `${percent}%`;
    bar.style.backgroundColor = skill.color;
    bar.style.boxShadow = `0 0 10px ${skill.color}`;
    const subText = card.createEl("div", { cls: "lg-stat-values" });
    subText.createEl("span", { text: `${Math.floor(remainingXp)} / ${requiredXp}`, cls: "lg-xp-text" });
    subText.createEl("span", { text: `Lv.${level}`, cls: "lg-level-text" });
  }
  renderProgressBar(parent, stat) {
    const { level, remainingXp, requiredXp } = calculateLevel(stat.currentXp, stat.baseXp, stat.xpIncrement);
    const percent = Math.min(100, remainingXp / requiredXp * 100);
    const statRow = parent.createEl("div", { cls: "lg-stat-row" });
    statRow.createEl("span", { text: `${stat.icon} ${stat.name}`, cls: "lg-stat-label" });
    const barContainer = statRow.createEl("div", { cls: "lg-bar-container" });
    const bar = barContainer.createEl("div", { cls: "lg-bar-fill" });
    bar.style.width = `${percent}%`;
    bar.style.backgroundColor = stat.color;
    const subText = statRow.createEl("div", { cls: "lg-stat-values" });
    subText.createEl("span", { text: `${Math.floor(remainingXp)} / ${requiredXp}`, cls: "lg-xp-text" });
    subText.createEl("span", { text: `Lv.${level}`, cls: "lg-level-text" });
  }
  renderQuests(parent, tasks) {
    parent.createEl("h3", { text: "Today quest", cls: "lg-section-title" });
    const questHeader = parent.createEl("div", { cls: "lg-quest-header" });
    const questList = parent.createEl("div", { cls: "lg-quest-list" });
    if (tasks.length === 0) {
      questList.createEl("div", { cls: "lg-no-tasks", text: "Kh\xF4ng c\xF3 nhi\u1EC7m v\u1EE5 n\xE0o h\xF4m nay." });
      return;
    }
    tasks.forEach((task) => {
      const item = questList.createEl("div", { cls: `lg-quest-item ${task.completed ? "is-completed" : ""}` });
      const checkbox = item.createEl("input", { type: "checkbox" });
      checkbox.checked = task.completed;
      checkbox.disabled = task.isProcessed;
      if (!task.isProcessed) {
        checkbox.addEventListener("change", () => this.handleTaskToggle(task, checkbox.checked));
      }
      const textContainer = item.createEl("div", { cls: "lg-quest-text-container" });
      textContainer.createEl("span", { text: task.text, cls: "lg-quest-title" });
      if (task.rewards.length > 0 || task.skills.length > 0 || task.date || task.time) {
        const meta = textContainer.createEl("div", { cls: "lg-quest-meta" });
        if (task.rewards.length > 0) {
          const rewardsText = task.rewards.map((r) => {
            const stat = this.plugin.settings.stats.find((s) => s.id === r.statId);
            return `+${r.amount} ${stat ? stat.name : r.statId}`;
          }).join(", ");
          meta.createEl("span", { text: `(${rewardsText})`, cls: "lg-reward-text" });
        }
        if (task.date || task.time) {
          const dateTimeText = `${task.date || ""} ${task.time || ""}`.trim();
          meta.createEl("span", { text: ` \u{1F4C5} ${dateTimeText}`, cls: "lg-date-text" });
        }
        if (task.skills.length > 0) {
          const skillsText = task.skills.map((s) => `#${s}`).join(" ");
          meta.createEl("span", { text: ` ${skillsText}`, cls: "lg-skill-tag" });
        }
      }
    });
  }
  async handleTaskToggle(task, completed) {
    if (task.isProcessed)
      return;
    const file = this.app.vault.getAbstractFileByPath(this.plugin.settings.taskFilePath);
    if (!(file instanceof import_obsidian.TFile))
      return;
    this.plugin.isInternalChange = true;
    try {
      const content = await this.app.vault.read(file);
      const newContent = updateTaskInContent(content, task.originalLine, completed, completed);
      await this.app.vault.modify(file, newContent);
      this.plugin.lastKnownContent = newContent;
      const oldTotalXp = getTotalXp(this.plugin.settings.stats);
      const currentTitle = getCurrentTitle(oldTotalXp, this.plugin.settings.titles);
      const taskId = getTaskKey(task);
      const now = /* @__PURE__ */ new Date();
      const penaltyInfo = this.plugin.getPenaltyInfo(task, now);
      if (completed) {
        this.plugin.applyReward(task, penaltyInfo);
        this.plugin.settings.completedTasks.push(taskId);
      } else {
        this.plugin.applyUnreward(task);
        const index = this.plugin.settings.completedTasks.indexOf(taskId);
        if (index > -1) {
          this.plugin.settings.completedTasks.splice(index, 1);
        }
      }
      const rewardsList = task.rewards.map((r) => {
        const stat = this.plugin.settings.stats.find((s) => s.id === r.statId);
        const finalAmount = Math.round(r.amount * penaltyInfo.multiplier * 10) / 10;
        return `${finalAmount > 0 ? "+" : ""}${finalAmount} ${stat ? stat.name : r.statId}`;
      }).join(", ");
      const rewardMsg = rewardsList ? ` (${rewardsList})` : "";
      if (completed && penaltyInfo.isLate) {
        const reductionPercent = Math.round((1 - penaltyInfo.multiplier) * 100);
        const statusMsg = penaltyInfo.multiplier < 0 ? `B\u1ECB tr\u1EEB ${-Math.round(penaltyInfo.multiplier * 100)}% \u0111i\u1EC3m` : `Gi\u1EA3m ${reductionPercent}% \u0111i\u1EC3m`;
        new import_obsidian.Notice(`\u26A0\uFE0F Ho\xE0n th\xE0nh tr\u1EC5: ${task.text}${rewardMsg}
${statusMsg} do tr\u1EC5 ${penaltyInfo.minutesLate} ph\xFAt.`, 5e3);
      } else if (completed) {
        new import_obsidian.Notice(`\u2705 Nhi\u1EC7m v\u1EE5 ho\xE0n th\xE0nh: ${task.text}${rewardMsg}`);
      }
      await this.plugin.saveSettings();
      const newTotalXp = getTotalXp(this.plugin.settings.stats);
      const newTitle = getCurrentTitle(newTotalXp, this.plugin.settings.titles);
      if (completed && newTitle.name !== currentTitle.name) {
        new import_obsidian.Notice(`\u{1F389} CH\xDAC M\u1EEANG! \u{1F389}
B\u1EA1n \u0111\xE3 \u0111\u1EA1t c\u1EA5p \u0111\u1ED9 m\u1EDBi: ${newTitle.name}!`, 5e3);
      }
    } finally {
      this.plugin.isInternalChange = false;
    }
  }
};

// main.ts
var LifeGaugePlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "isInternalChange", false);
    __publicField(this, "isSyncing", false);
    __publicField(this, "pendingSync", false);
    __publicField(this, "lastKnownContent", "");
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_LIFE_GAUGE,
      (leaf) => new LifeGaugeView(leaf, this)
    );
    this.addRibbonIcon("gamepad", "Open Life Gauge", () => {
      this.activateView();
    });
    this.addSettingTab(new LifeGaugeSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (this.isInternalChange)
          return;
        if (file instanceof import_obsidian2.TFile && file.path === this.settings.taskFilePath) {
          await this.syncTasksFromFile(file);
        }
      })
    );
  }
  applyReward(task, penaltyInfo) {
    task.rewards.forEach((reward) => {
      const stat = this.settings.stats.find((s) => s.id === reward.statId);
      if (stat) {
        const finalReward = reward.amount * penaltyInfo.multiplier;
        stat.currentXp += finalReward;
        if (stat.currentXp < 0)
          stat.currentXp = 0;
      }
    });
    task.skills.forEach((skillName) => {
      const skill = this.settings.skills.find((s) => s.name.toLowerCase() === skillName || s.id.toLowerCase() === skillName);
      if (skill) {
        const totalReward = task.rewards.reduce((sum, r) => sum + r.amount, 0) || 10;
        const finalReward = totalReward * penaltyInfo.multiplier;
        skill.currentXp += finalReward;
        if (skill.currentXp < 0)
          skill.currentXp = 0;
      }
    });
  }
  applyUnreward(task) {
    task.rewards.forEach((reward) => {
      const stat = this.settings.stats.find((s) => s.id === reward.statId);
      if (stat)
        stat.currentXp = Math.max(0, stat.currentXp - reward.amount);
    });
    task.skills.forEach((skillName) => {
      const skill = this.settings.skills.find((s) => s.name.toLowerCase() === skillName || s.id.toLowerCase() === skillName);
      if (skill) {
        const totalReward = task.rewards.reduce((sum, r) => sum + r.amount, 0) || 10;
        skill.currentXp = Math.max(0, skill.currentXp - totalReward);
      }
    });
  }
  showRewardNotice(task, penaltyInfo) {
    const rewardsList = task.rewards.map((r) => {
      const stat = this.settings.stats.find((s) => s.id === r.statId);
      const finalAmount = Math.round(r.amount * penaltyInfo.multiplier * 10) / 10;
      return `${finalAmount > 0 ? "+" : ""}${finalAmount} ${stat ? stat.name : r.statId}`;
    }).join(", ");
    const rewardMsg = rewardsList ? ` (${rewardsList})` : "";
    if (penaltyInfo.isLate) {
      const reductionPercent = Math.round((1 - penaltyInfo.multiplier) * 100);
      const statusMsg = penaltyInfo.multiplier < 0 ? `B\u1ECB tr\u1EEB ${-Math.round(penaltyInfo.multiplier * 100)}% \u0111i\u1EC3m` : `Gi\u1EA3m ${reductionPercent}% \u0111i\u1EC3m`;
      new import_obsidian2.Notice(`\u26A0\uFE0F Ho\xE0n th\xE0nh tr\u1EC5: ${task.text}${rewardMsg}
${statusMsg} do tr\u1EC5 ${penaltyInfo.minutesLate} ph\xFAt.`, 5e3);
    } else {
      new import_obsidian2.Notice(`\u2705 Nhi\u1EC7m v\u1EE5 ho\xE0n th\xE0nh: ${task.text}${rewardMsg}`);
    }
  }
  async syncTasksFromFile(file) {
    if (this.isSyncing) {
      this.pendingSync = true;
      return;
    }
    this.isSyncing = true;
    try {
      const content = await this.app.vault.read(file);
      if (content === this.lastKnownContent)
        return;
      const oldTasks = this.lastKnownContent ? parseTasks(this.lastKnownContent, this.settings.stats) : [];
      const newTasks = parseTasks(content, this.settings.stats);
      const now = /* @__PURE__ */ new Date();
      let changed = false;
      let fileContentChanged = false;
      let currentContent = content;
      const newlyCompleted = newTasks.filter((t) => t.completed && !t.isProcessed);
      for (const task of newlyCompleted) {
        const key = getTaskKey(task);
        if (!this.settings.completedTasks.includes(key)) {
          const penaltyInfo = this.getPenaltyInfo(task, now);
          this.applyReward(task, penaltyInfo);
          this.settings.completedTasks.push(key);
          this.showRewardNotice(task, penaltyInfo);
          changed = true;
        }
        currentContent = updateTaskInContent(currentContent, task.originalLine, true, true);
        fileContentChanged = true;
      }
      const unprocessedOld = oldTasks.filter((t) => t.completed && !t.isProcessed);
      for (const oldTask of unprocessedOld) {
        const stillChecked = newTasks.some((nt) => nt.originalLine === oldTask.originalLine && nt.completed);
        if (!stillChecked) {
          const key = getTaskKey(oldTask);
          if (this.settings.completedTasks.includes(key)) {
            this.applyUnreward(oldTask);
            const idx = this.settings.completedTasks.indexOf(key);
            if (idx > -1)
              this.settings.completedTasks.splice(idx, 1);
            changed = true;
          }
        }
      }
      if (fileContentChanged && currentContent !== content) {
        this.isInternalChange = true;
        await this.app.vault.modify(file, currentContent);
        this.lastKnownContent = currentContent;
        this.isInternalChange = false;
      } else {
        this.lastKnownContent = content;
      }
      if (changed) {
        await this.saveSettings();
      } else if (fileContentChanged) {
        this.refreshViews();
      }
    } finally {
      this.isSyncing = false;
      if (this.pendingSync) {
        this.pendingSync = false;
        const file2 = this.app.vault.getAbstractFileByPath(this.settings.taskFilePath);
        if (file2 instanceof import_obsidian2.TFile) {
          await this.syncTasksFromFile(file2);
        }
      }
    }
  }
  getPenaltyInfo(task, now) {
    if (!task.date && !task.time)
      return { multiplier: 1, isLate: false, minutesLate: 0 };
    let deadline;
    if (task.date && task.time) {
      deadline = /* @__PURE__ */ new Date(`${task.date}T${task.time}`);
    } else if (task.date) {
      deadline = /* @__PURE__ */ new Date(`${task.date}T23:59:59`);
    } else {
      const today = now.toISOString().split("T")[0];
      deadline = /* @__PURE__ */ new Date(`${today}T${task.time}`);
    }
    if (now <= deadline)
      return { multiplier: 1, isLate: false, minutesLate: 0 };
    const minutesLate = Math.floor((now.getTime() - deadline.getTime()) / (1e3 * 60));
    const multiplier = 1 - minutesLate * this.settings.penaltyPoint / 100;
    return { multiplier, isLate: true, minutesLate };
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    const file = this.app.vault.getAbstractFileByPath(this.settings.taskFilePath);
    if (file instanceof import_obsidian2.TFile) {
      this.lastKnownContent = await this.app.vault.read(file);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshViews();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_LIFE_GAUGE)[0];
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({
        type: VIEW_TYPE_LIFE_GAUGE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_LIFE_GAUGE).forEach((leaf) => {
      if (leaf.view instanceof LifeGaugeView) {
        leaf.view.update();
      }
    });
  }
};
var LifeGaugeSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Life Gauge Settings" });
    new import_obsidian2.Setting(containerEl).setName("Avatar Path").setDesc("Path to your avatar image in the vault.").addText((text) => text.setValue(this.plugin.settings.avatarPath).onChange(async (value) => {
      this.plugin.settings.avatarPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Task File Path").setDesc("Path to the Markdown file containing your tasks.").addText((text) => text.setValue(this.plugin.settings.taskFilePath).onChange(async (value) => {
      this.plugin.settings.taskFilePath = value;
      const file = this.app.vault.getAbstractFileByPath(value);
      if (file instanceof import_obsidian2.TFile) {
        this.plugin.lastKnownContent = await this.app.vault.read(file);
      } else {
        this.plugin.lastKnownContent = "";
      }
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u{1F480} C\u1EA5u h\xECnh h\xECnh ph\u1EA1t" });
    new import_obsidian2.Setting(containerEl).setName("H\u1EC7 s\u1ED1 h\xECnh ph\u1EA1t (Penalty Point)").setDesc("S\u1ED1 \u0111i\u1EC3m c\xE0ng cao, h\xECnh ph\u1EA1t tr\u1EC5 h\u1EA1n c\xE0ng n\u1EB7ng. C\xF4ng th\u1EE9c: Points - (Ph\xFAt tr\u1EC5 * Points / 100) * PenaltyPoint").addText((text) => text.setPlaceholder("1").setValue(this.plugin.settings.penaltyPoint.toString()).onChange(async (value) => {
      const val = parseFloat(value);
      if (!isNaN(val)) {
        this.plugin.settings.penaltyPoint = val;
        await this.plugin.saveSettings();
      }
    }));
    const statsDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const statsSummary = statsDetails.createEl("summary");
    statsSummary.createEl("h3", { text: "Stats Configuration", cls: "lg-settings-summary-title" });
    this.plugin.settings.stats.forEach((stat, index) => {
      const statHeader = statsDetails.createEl("div", { cls: "lg-setting-stat-header" });
      statHeader.style.display = "flex";
      statHeader.style.justifyContent = "space-between";
      statHeader.style.alignItems = "center";
      const titleEl = statHeader.createEl("h4", { text: stat.name });
      titleEl.style.margin = "0";
      const deleteBtn = statHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.stats.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian2.Setting(statsDetails).setName("Stat Name").addText((text) => text.setValue(stat.name).onChange(async (value) => {
        this.plugin.settings.stats[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(statsDetails).setName("Stat Icon").addText((text) => text.setValue(stat.icon).onChange(async (value) => {
        this.plugin.settings.stats[index].icon = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(statsDetails).setName(`${stat.name} Color`).setDesc(`Color for the ${stat.name} progress bar.`).addColorPicker((color) => color.setValue(stat.color).onChange(async (value) => {
        this.plugin.settings.stats[index].color = value;
        await this.plugin.saveSettings();
      }));
      statsDetails.createEl("hr");
    });
    new import_obsidian2.Setting(statsDetails).setName("Add New Stat").setDesc("Create a new attribute to track.").addButton((btn) => btn.setButtonText("Add Stat").onClick(async () => {
      this.plugin.settings.stats.push({
        id: `stat-${Date.now()}`,
        name: "New Stat",
        icon: "\u2B50",
        currentXp: 0,
        level: 1,
        color: "#cccccc",
        baseXp: 100,
        xpIncrement: 50
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    const skillsDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const skillsSummary = skillsDetails.createEl("summary");
    skillsSummary.createEl("h3", { text: "Skills Configuration", cls: "lg-settings-summary-title" });
    this.plugin.settings.skills.forEach((skill, index) => {
      const skillHeader = skillsDetails.createEl("div", { cls: "lg-setting-stat-header" });
      skillHeader.style.display = "flex";
      skillHeader.style.justifyContent = "space-between";
      skillHeader.style.alignItems = "center";
      const titleEl = skillHeader.createEl("h4", { text: skill.name });
      titleEl.style.margin = "0";
      const deleteBtn = skillHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.skills.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian2.Setting(skillsDetails).setName("Skill Name").addText((text) => text.setValue(skill.name).onChange(async (value) => {
        this.plugin.settings.skills[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(skillsDetails).setName("Skill Icon").addText((text) => text.setValue(skill.icon).onChange(async (value) => {
        this.plugin.settings.skills[index].icon = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(skillsDetails).setName(`${skill.name} Color`).addColorPicker((color) => color.setValue(skill.color).onChange(async (value) => {
        this.plugin.settings.skills[index].color = value;
        await this.plugin.saveSettings();
      }));
      skillsDetails.createEl("hr");
    });
    new import_obsidian2.Setting(skillsDetails).setName("Create New Skill").setDesc("Skills track your real-world progress (e.g., English, Java).").addButton((btn) => btn.setButtonText("Add Skill").onClick(async () => {
      this.plugin.settings.skills.push({
        id: `skill-${Date.now()}`,
        name: "New Skill",
        icon: "\u{1F3AF}",
        currentXp: 0,
        level: 1,
        color: "#8e44ad",
        baseXp: 100,
        xpIncrement: 50
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    const titlesDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const titlesSummary = titlesDetails.createEl("summary");
    titlesSummary.createEl("h3", { text: "\u{1F3C6} Titles configuration", cls: "lg-settings-summary-title" });
    this.plugin.settings.titles.forEach((title, index) => {
      const titleHeader = titlesDetails.createEl("div", { cls: "lg-setting-stat-header" });
      titleHeader.style.display = "flex";
      titleHeader.style.justifyContent = "space-between";
      titleHeader.style.alignItems = "center";
      const titleLabel = titleHeader.createEl("h4", { text: title.name });
      titleLabel.style.margin = "0";
      const deleteBtn = titleHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.titles.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian2.Setting(titlesDetails).setName("T\xEAn danh hi\u1EC7u").addText((text) => text.setValue(title.name).onChange(async (value) => {
        this.plugin.settings.titles[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(titlesDetails).setName("Icon").addText((text) => text.setValue(title.icon).onChange(async (value) => {
        this.plugin.settings.titles[index].icon = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(titlesDetails).setName("M\u1ED1c XP (Threshold)").setDesc("L\u01B0\u1EE3ng XP c\u1EA7n \u0111\u1EA1t \u0111\u1EC3 nh\u1EADn danh hi\u1EC7u n\xE0y.").addText((text) => text.setValue(title.threshold.toString()).onChange(async (value) => {
        const val = parseInt(value);
        if (!isNaN(val)) {
          this.plugin.settings.titles[index].threshold = val;
          await this.plugin.saveSettings();
        }
      }));
      new import_obsidian2.Setting(titlesDetails).setName("M\xF4 t\u1EA3").addTextArea((text) => text.setValue(title.description).onChange(async (value) => {
        this.plugin.settings.titles[index].description = value;
        await this.plugin.saveSettings();
      }));
      titlesDetails.createEl("hr");
    });
    new import_obsidian2.Setting(titlesDetails).setName("Th\xEAm Danh hi\u1EC7u m\u1EDBi").addButton((btn) => btn.setButtonText("Th\xEAm Danh hi\u1EC7u").onClick(async () => {
      this.plugin.settings.titles.push({
        threshold: 0,
        name: "Danh hi\u1EC7u m\u1EDBi",
        icon: "\u{1F195}",
        description: "M\xF4 t\u1EA3 v\u1EC1 danh hi\u1EC7u n\xE0y..."
      });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
};
