/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LifeGaugePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/data.ts
var DEFAULT_STATS = [
  {
    id: "stamina",
    name: "Stamina",
    icon: "\u{1F4AA}",
    currentXp: 0,
    level: 1,
    color: "#4dff88",
    baseXp: 100,
    xpIncrement: 50
  },
  {
    id: "strength",
    name: "Strength",
    icon: "\u{1F9E0}",
    currentXp: 0,
    level: 1,
    color: "#ffaa4d",
    baseXp: 100,
    xpIncrement: 50
  },
  {
    id: "knowledge",
    name: "Knowledge",
    icon: "\u{1F4DA}",
    currentXp: 0,
    level: 1,
    color: "#4da6ff",
    baseXp: 100,
    xpIncrement: 50
  }
];
var DEFAULT_TITLES = [
  {
    threshold: 0,
    name: "The Outcast",
    icon: "\u2694\uFE0F",
    description: "You always feel inadequate and left behind. You fail at most things and doubt your own abilities. Don't give up, keep trying!"
  },
  {
    threshold: 300,
    name: "The Traveler",
    icon: "\u{1F6B6}",
    description: "You've started to find your way. The first steps are always the hardest, but every day you become more steady."
  },
  {
    threshold: 800,
    name: "The Awakened",
    icon: "\u{1F525}",
    description: "A small fire has ignited within you. You realize that you can do more than you think."
  },
  {
    threshold: 1500,
    name: "Resilient Warrior",
    icon: "\u{1F6E1}\uFE0F",
    description: "Challenges no longer make you flinch. You have trained enough to stand firm in the storm."
  },
  {
    threshold: 3e3,
    name: "Master",
    icon: "\u{1F451}",
    description: "Your skills have become legendary in your own community. Others look to you for inspiration."
  },
  {
    threshold: 5e3,
    name: "Living Legend",
    icon: "\u{1F31F}",
    description: "You have surpassed the limits of ordinary humans. Your story will be told for generations."
  }
];
var DEFAULT_SETTINGS = {
  avatarPath: ".life-gauge/avatar.png",
  taskFilePath: "Daily/quests.md",
  stats: DEFAULT_STATS,
  titles: DEFAULT_TITLES,
  skills: [],
  completedTasks: [],
  penaltyPoint: 1,
  refreshInterval: 5,
  hunger: 100,
  maxHunger: 100,
  coins: 0,
  lastHungerUpdate: Date.now(),
  customShopItems: [],
  dailyXpLogs: {},
  ai: {
    enabled: false,
    name: "Companion",
    interval: 60,
    provider: "gemini",
    apiKey: "",
    model: "gemini-pro",
    newResponse: false
  },
  lastAiResponse: "Hello! I am your companion. Keep me full and be productive!",
  lastAiTriggerTime: Date.now()
};
function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function calculateLevel(currentXp, baseXp, xpIncrement) {
  let level = 1;
  let xpNeeded = baseXp;
  let tempXp = currentXp;
  while (tempXp >= xpNeeded) {
    tempXp -= xpNeeded;
    level++;
    xpNeeded = baseXp + (level - 1) * xpIncrement;
  }
  const progress = tempXp / xpNeeded * 100;
  return { level, remainingXp: tempXp, requiredXp: xpNeeded, progress };
}
function getTotalXp(stats) {
  return stats.reduce((acc, stat) => acc + stat.currentXp, 0);
}
function getCurrentTitle(totalXp, titles) {
  const sortedTitles = [...titles].sort((a, b) => b.threshold - a.threshold);
  return sortedTitles.find((t) => totalXp >= t.threshold) || titles[0];
}
function getNextTitle(totalXp, titles) {
  const sortedTitles = [...titles].sort((a, b) => a.threshold - b.threshold);
  return sortedTitles.find((t) => t.threshold > totalXp) || null;
}

// src/view.ts
var import_obsidian = require("obsidian");

// src/parser.ts
function getTaskKey(task) {
  const statsKey = (task.rewards || []).map((r) => r.statId).sort().join(",");
  return `${task.text}:${statsKey}:${task.date || ""}:${task.time || ""}:${task.occurrenceIndex}`;
}
function parseTasks(content, stats) {
  const lines = content.split("\n");
  const tasks = [];
  const taskRegex = /^\s*-\s*\[([ x])\]\s*(.+?)\s*$/;
  const rewardSectionRegex = /\(([^)]+)\)/;
  const rewardRegex = /\+([0-9]+)\s+([a-zA-Z0-9-]+)/g;
  const dateRegex = /@\{([^}]+)\}/;
  const timeRegex = /@@\{([^}]+)\}/;
  const skillRegex = /#([a-zA-Z0-9\u00C0-\u1EF9-]+)/g;
  let isArchivedSection = false;
  const occurrenceMap = /* @__PURE__ */ new Map();
  lines.forEach((line, index) => {
    if (line.trim().toLowerCase().startsWith("## archive")) {
      isArchivedSection = true;
      return;
    }
    const match = taskRegex.exec(line);
    if (match) {
      const isProcessed = line.trim().endsWith("(done)");
      const completed = match[1] === "x";
      let remainingText = match[2];
      if (isProcessed) {
        remainingText = remainingText.replace(/\s*\(done\)$/, "").trim();
      }
      const rewards = [];
      const statMatch = rewardSectionRegex.exec(remainingText);
      if (statMatch) {
        const statsRaw = statMatch[1];
        const statNames = statsRaw.split(",").map((s) => s.trim().toLowerCase());
        statNames.forEach((name) => {
          const stat = stats.find((s) => s.name.toLowerCase() === name || s.id.toLowerCase() === name);
          if (stat) {
            rewards.push({ statId: stat.id, amount: 0 });
          }
        });
        remainingText = remainingText.replace(rewardSectionRegex, "").trim();
      }
      let date;
      const dMatch = dateRegex.exec(remainingText);
      if (dMatch) {
        date = dMatch[1];
        remainingText = remainingText.replace(dateRegex, "").trim();
      }
      let time;
      const tMatch = timeRegex.exec(remainingText);
      if (tMatch) {
        time = tMatch[1];
        remainingText = remainingText.replace(timeRegex, "").trim();
      }
      const skills = [];
      let sMatch;
      while ((sMatch = skillRegex.exec(remainingText)) !== null) {
        skills.push(sMatch[1].toLowerCase());
      }
      remainingText = remainingText.replace(skillRegex, "").trim();
      if (!date && !time)
        return;
      const baseKey = `${remainingText}:${rewards.map((r) => r.statId).sort().join(",")}:${date || ""}:${time || ""}`;
      const occurrenceIndex = occurrenceMap.get(baseKey) || 0;
      occurrenceMap.set(baseKey, occurrenceIndex + 1);
      const task = {
        originalLine: index,
        text: remainingText,
        completed,
        rewards,
        skills,
        date,
        time,
        isArchived: isArchivedSection,
        isProcessed,
        occurrenceIndex
      };
      if (isProcessed && index + 1 < lines.length) {
        const nextLine = lines[index + 1];
        const coinMatch = /\+💰\s*(\d+)/.exec(nextLine);
        if (coinMatch) {
          task.earnedCoins = parseInt(coinMatch[1]);
        }
        task.rewards.forEach((r) => {
          const stat = stats.find((s) => s.id === r.statId);
          if (stat) {
            const xpRegex = new RegExp(`\\+([\\d.]+)\\s+${stat.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "i");
            const xpMatch = xpRegex.exec(nextLine);
            if (xpMatch) {
              r.earnedAmount = parseFloat(xpMatch[1]);
            }
          }
        });
      }
      tasks.push(task);
    }
  });
  return tasks;
}
function updateTaskInContent(content, lineIndex, completed, addDone = false, rewardText) {
  const lines = content.split("\n");
  if (lineIndex >= 0 && lineIndex < lines.length) {
    if (addDone) {
      lines[lineIndex] = lines[lineIndex].replace(/\[[ x]\]/, `[x]`);
      if (!lines[lineIndex].trim().endsWith("(done)")) {
        lines[lineIndex] = lines[lineIndex].trimEnd() + " (done)";
      }
      if (rewardText) {
        const indentMatch = lines[lineIndex].match(/^(\s*)/);
        const indent = indentMatch ? indentMatch[1] : "";
        lines[lineIndex] = lines[lineIndex] + `
${indent}  ${rewardText}`;
      }
    } else {
      const char = completed ? "x" : " ";
      lines[lineIndex] = lines[lineIndex].replace(/\[[ x]\]/, `[${char}]`);
    }
  }
  return lines.join("\n");
}

// src/view.ts
var VIEW_TYPE_LIFE_GAUGE = "life-gauge-view";
var LifeGaugeView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "tasks", []);
    __publicField(this, "isUpdating", false);
    __publicField(this, "activeTab", "main");
    __publicField(this, "purchasedItemIds", /* @__PURE__ */ new Set());
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_LIFE_GAUGE;
  }
  getDisplayText() {
    return "Life Gauge";
  }
  getIcon() {
    return "gamepad";
  }
  async onOpen() {
    this.update();
  }
  async update() {
    if (this.isUpdating)
      return;
    this.isUpdating = true;
    try {
      await this.loadTasks();
      const visibleTasks = this.tasks.filter((t) => !t.isArchived);
      const totalXp = getTotalXp(this.plugin.settings.stats);
      const title = getCurrentTitle(totalXp, this.plugin.settings.titles);
      const nextTitle = getNextTitle(totalXp, this.plugin.settings.titles);
      const { contentEl } = this;
      contentEl.empty();
      contentEl.addClass("life-gauge-dashboard");
      this.renderHeader(contentEl, title, nextTitle, totalXp);
      if (this.activeTab === "shop") {
        this.renderShop(contentEl);
      } else if (this.activeTab === "stats") {
        this.renderStatsTab(contentEl);
      } else {
        this.renderStats(contentEl);
        if (this.plugin.settings.skills.length > 0) {
          this.renderSkills(contentEl);
        }
        this.renderQuests(contentEl, visibleTasks);
      }
    } catch (e) {
      console.error("Life Gauge: Update failed", e);
    } finally {
      this.isUpdating = false;
    }
  }
  async loadTasks() {
    const file = this.app.vault.getAbstractFileByPath(this.plugin.settings.taskFilePath);
    if (file instanceof import_obsidian.TFile) {
      const content = await this.app.vault.read(file);
      this.tasks = parseTasks(content, this.plugin.settings.stats);
    } else {
      this.tasks = [];
    }
  }
  renderHeader(parent, title, nextTitle, totalXp) {
    const header = parent.createEl("div", { cls: "lg-header" });
    const topBar = header.createEl("div", { cls: "lg-header-top-bar" });
    this.renderSatiety(topBar);
    const coinsSettingsGroup = topBar.createEl("div", { cls: "lg-coins-shop-group" });
    const coinContainer = coinsSettingsGroup.createEl("div", { cls: "lg-coin-container" });
    coinContainer.createEl("span", { text: `\u{1F4B0} ${Math.floor(this.plugin.settings.coins)}`, cls: "lg-coin-text" });
    const settingsIcon = coinsSettingsGroup.createEl("div", { cls: "lg-settings-icon", text: "\u2699\uFE0F" });
    settingsIcon.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById(this.plugin.manifest.id);
    });
    const tabNav = header.createEl("div", { cls: "lg-tab-nav" });
    const tabs = [
      { id: "main", name: "Dashboard", icon: "\u{1F3E0}" },
      { id: "shop", name: "Shop", icon: "\u{1F3EA}" },
      { id: "stats", name: "Stats", icon: "\u{1F4CA}" }
    ];
    tabs.forEach((t) => {
      const tabBtn = tabNav.createEl("button", { cls: `lg-tab-btn ${this.activeTab === t.id ? "is-active" : ""}` });
      tabBtn.createEl("span", { text: t.icon, cls: "lg-tab-icon" });
      tabBtn.createEl("span", { text: t.name, cls: "lg-tab-name" });
      tabBtn.addEventListener("click", () => {
        this.activeTab = t.id;
        this.update();
      });
    });
    const mainInfo = header.createEl("div", { cls: "lg-header-main" });
    const avatarContainer = mainInfo.createEl("div", { cls: "lg-avatar-container" });
    const avatar = avatarContainer.createEl("img", {
      cls: "lg-avatar",
      attr: {
        src: this.app.vault.adapter.getResourcePath(this.plugin.settings.avatarPath),
        title: this.plugin.settings.ai.enabled ? `Click to talk to ${this.plugin.settings.ai.name}` : ""
      }
    });
    if (this.plugin.settings.ai.enabled) {
      avatar.addEventListener("click", async () => {
        new import_obsidian.Notice(`${this.plugin.settings.ai.name} is thinking...`);
        await this.plugin.triggerAiAnalysis("I'm checking in on you!");
        new import_obsidian.Notice(`${this.plugin.settings.ai.name} has spoken!`);
        this.update();
      });
    }
    const info = mainInfo.createEl("div", { cls: "lg-info" });
    let displayName = `${title.icon} ${title.name.toUpperCase()} ${title.icon}`;
    let displayDesc = title.description;
    if (this.plugin.settings.ai.enabled) {
      displayName = this.plugin.settings.ai.name.toUpperCase();
      displayDesc = this.plugin.settings.lastAiResponse;
    }
    info.createEl("div", { cls: "lg-nickname", text: displayName });
    const descEl = info.createEl("div", { cls: "lg-description" });
    if (this.plugin.settings.ai.enabled && this.plugin.settings.ai.newResponse) {
      this.runTypewriter(descEl, displayDesc);
      this.plugin.settings.ai.newResponse = false;
      this.plugin.saveSettings();
    } else {
      descEl.textContent = displayDesc;
    }
    if (this.plugin.settings.ai.enabled) {
      return;
    }
    if (nextTitle) {
      const neededForNext = nextTitle.threshold - totalXp;
      info.createEl("div", { cls: "lg-next-rank", text: `\u{1F51C} ${neededForNext} XP to become ${nextTitle.name}` });
    } else {
      info.createEl("div", { cls: "lg-next-rank", text: `\u{1F3C6} You have reached the pinnacle of glory!` });
    }
  }
  async runTypewriter(el, text, speed = 25) {
    el.textContent = "";
    for (let i = 0; i < text.length; i++) {
      el.textContent += text.charAt(i);
      await new Promise((resolve) => setTimeout(resolve, speed));
    }
  }
  renderSatiety(parent) {
    const hunger = this.plugin.settings.hunger;
    const maxHunger = this.plugin.settings.maxHunger;
    const percent = hunger / maxHunger * 100;
    const container = parent.createEl("div", { cls: "lg-satiety-container" });
    container.createEl("div", { text: "\u{1F356} Satiety", cls: "lg-satiety-label" });
    const barContainer = container.createEl("div", { cls: "lg-bar-container satiety" });
    const bar = barContainer.createEl("div", { cls: "lg-bar-fill" });
    bar.style.width = `${Math.min(100, percent)}%`;
    if (percent >= 70) {
      bar.style.backgroundColor = "#4dff88";
    } else if (percent >= 30) {
      bar.style.backgroundColor = "#ffcc00";
    } else {
      bar.style.backgroundColor = "#ff4d4d";
    }
    container.createEl("div", { text: `${Math.floor(hunger)} / ${maxHunger}`, cls: "lg-satiety-value" });
  }
  renderShop(parent) {
    const shopContainer = parent.createEl("div", { cls: "lg-shop-container" });
    shopContainer.createEl("h3", { text: "\u{1F3EA} Food Shop", cls: "lg-section-title" });
    const shopGrid = shopContainer.createEl("div", { cls: "lg-shop-grid" });
    const items = [
      { icon: "\u{1F352}", name: "Cherry", boost: 5, cost: 10 },
      { icon: "\u{1F34C}", name: "Banana", boost: 7, cost: 14 },
      { icon: "\u{1F35E}", name: "Bread", boost: 15, cost: 24 },
      { icon: "\u{1F371}", name: "Meal", boost: 25, cost: 40 }
    ];
    items.forEach((item) => {
      const card = shopGrid.createEl("div", { cls: "lg-shop-card" });
      card.createEl("div", { text: item.icon, cls: "lg-shop-item-icon" });
      card.createEl("div", { text: item.name, cls: "lg-shop-item-name" });
      card.createEl("div", { text: `+${item.boost} Satiety`, cls: "lg-shop-item-boost" });
      const buyBtn = card.createEl("button", {
        text: `${item.cost} \u{1F4B0} Buy`,
        cls: "lg-buy-btn"
      });
      if (this.plugin.settings.coins < item.cost) {
        buyBtn.setAttr("disabled", true);
        buyBtn.addClass("is-disabled");
      }
      buyBtn.addEventListener("click", async () => {
        if (this.plugin.settings.coins >= item.cost) {
          this.plugin.settings.coins -= item.cost;
          this.plugin.settings.hunger = Math.min(this.plugin.settings.maxHunger, this.plugin.settings.hunger + item.boost);
          new import_obsidian.Notice(`Consumed ${item.name}! +${item.boost} Satiety.`);
          const aiPrompt = `I just bought and consumed ${item.name} for ${item.cost} coins. My satiety increased by ${item.boost} points! Mmm, delicious.`;
          await this.plugin.triggerAiAnalysis(aiPrompt);
          await this.plugin.saveSettings();
          this.update();
        }
      });
    });
    const customHeader = shopContainer.createEl("div", { cls: "lg-shop-section-header" });
    customHeader.createEl("h3", { text: "\u{1F381} Custom Rewards", cls: "lg-shop-section-title" });
    const addBtn = customHeader.createEl("button", { text: "\u2795", cls: "lg-add-reward-btn" });
    addBtn.setAttr("title", "Add new reward");
    addBtn.addEventListener("click", () => {
      this.plugin.showAddRewardModal();
    });
    if (this.plugin.settings.customShopItems.length > 0) {
      const customGrid = shopContainer.createEl("div", { cls: "lg-shop-grid" });
      this.plugin.settings.customShopItems.forEach((item) => {
        const isPurchased = this.purchasedItemIds.has(item.id);
        const card = customGrid.createEl("div", { cls: `lg-shop-card custom-reward ${isPurchased ? "lg-purchased-item" : ""}` });
        if (isPurchased) {
          card.createEl("div", { text: "\u2705 Received", cls: "lg-purchased-badge" });
        }
        card.createEl("div", { text: item.icon || "\u{1F381}", cls: "lg-shop-item-icon" });
        card.createEl("div", { text: item.name, cls: "lg-shop-item-name" });
        card.createEl("div", { text: item.description, cls: "lg-shop-item-desc" });
        const buyBtn = card.createEl("button", {
          text: isPurchased ? "Get more" : `${item.cost} \u{1F4B0} Claim`,
          cls: `lg-buy-btn ${isPurchased ? "is-purchased" : ""}`
        });
        if (this.plugin.settings.coins < item.cost) {
          buyBtn.setAttr("disabled", true);
          buyBtn.addClass("is-disabled");
        }
        buyBtn.addEventListener("click", async () => {
          if (this.plugin.settings.coins >= item.cost) {
            this.plugin.settings.coins -= item.cost;
            this.purchasedItemIds.add(item.id);
            new import_obsidian.Notice(`\u{1F389} Congratulations! You have received the reward: ${item.name}`);
            const aiPrompt = `I spent ${item.cost} coins to claim a custom reward: "${item.name}". I've earned this through my hard work!`;
            await this.plugin.triggerAiAnalysis(aiPrompt);
            await this.plugin.saveSettings();
            this.update();
          }
        });
      });
    } else {
      shopContainer.createEl("div", { text: "No custom items yet. Click + to add!", cls: "lg-no-items" });
    }
  }
  renderStats(parent) {
    const statsContainer = parent.createEl("div", { cls: "lg-stats-container" });
    this.plugin.settings.stats.forEach((stat) => this.renderProgressBar(statsContainer, stat));
  }
  renderSkills(parent) {
    parent.createEl("h3", { text: "Your skills", cls: "lg-section-title" });
    const skillsGrid = parent.createEl("div", { cls: "lg-skills-grid" });
    this.plugin.settings.skills.forEach((skill) => this.renderSkillCard(skillsGrid, skill));
  }
  renderSkillCard(parent, skill) {
    const card = parent.createEl("div", { cls: "lg-skill-card" });
    const { level, remainingXp, requiredXp } = calculateLevel(skill.currentXp, skill.baseXp, skill.xpIncrement);
    const percent = Math.min(100, remainingXp / requiredXp * 100);
    card.createEl("span", { text: `${skill.icon} ${skill.name}`, cls: "lg-stat-label" });
    const barContainer = card.createEl("div", { cls: "lg-bar-container" });
    const bar = barContainer.createEl("div", { cls: "lg-bar-fill" });
    bar.style.width = `${percent}%`;
    bar.style.backgroundColor = skill.color;
    bar.style.boxShadow = `0 0 10px ${skill.color}`;
    const subText = card.createEl("div", { cls: "lg-stat-values" });
    subText.createEl("span", { text: `${Math.floor(remainingXp)} / ${requiredXp}`, cls: "lg-xp-text" });
    subText.createEl("span", { text: `Lv.${level}`, cls: "lg-level-text" });
  }
  renderProgressBar(parent, stat) {
    const { level, remainingXp, requiredXp } = calculateLevel(stat.currentXp, stat.baseXp, stat.xpIncrement);
    const percent = Math.min(100, remainingXp / requiredXp * 100);
    const statRow = parent.createEl("div", { cls: "lg-stat-row" });
    statRow.createEl("span", { text: `${stat.icon} ${stat.name}`, cls: "lg-stat-label" });
    const barContainer = statRow.createEl("div", { cls: "lg-bar-container" });
    const bar = barContainer.createEl("div", { cls: "lg-bar-fill" });
    bar.style.width = `${percent}%`;
    bar.style.backgroundColor = stat.color;
    const subText = statRow.createEl("div", { cls: "lg-stat-values" });
    subText.createEl("span", { text: `${Math.floor(remainingXp)} / ${requiredXp}`, cls: "lg-xp-text" });
    subText.createEl("span", { text: `Lv.${level}`, cls: "lg-level-text" });
  }
  renderQuests(parent, tasks) {
    parent.createEl("h3", { text: "Today's Quest", cls: "lg-section-title" });
    const questHeader = parent.createEl("div", { cls: "lg-quest-header" });
    const questList = parent.createEl("div", { cls: "lg-quest-list" });
    if (tasks.length === 0) {
      questList.createEl("div", { cls: "lg-no-tasks", text: "No quests for today." });
      return;
    }
    tasks.forEach((task) => {
      const item = questList.createEl("div", { cls: `lg-quest-item ${task.completed ? "is-completed" : ""}` });
      const checkbox = item.createEl("input", { type: "checkbox" });
      checkbox.checked = task.completed;
      checkbox.disabled = task.isProcessed;
      if (!task.isProcessed) {
        checkbox.addEventListener("change", () => this.handleTaskToggle(task, checkbox.checked));
      }
      const textContainer = item.createEl("div", { cls: "lg-quest-text-container" });
      textContainer.createEl("span", { text: task.text, cls: "lg-quest-title" });
      if (task.rewards.length > 0 || task.skills.length > 0 || task.date || task.time) {
        const meta = textContainer.createEl("div", { cls: "lg-quest-meta" });
        if (task.rewards.length > 0) {
          let rewardsText = task.rewards.map((r) => {
            const stat = this.plugin.settings.stats.find((s) => s.id === r.statId);
            const label = stat ? stat.name : r.statId;
            if (task.isProcessed && r.earnedAmount !== void 0) {
              return `+${r.earnedAmount} ${label}`;
            }
            return label;
          }).join(", ");
          if (task.isProcessed && task.earnedCoins !== void 0) {
            rewardsText += ` +\u{1F4B0} ${task.earnedCoins} coin`;
          }
          meta.createEl("span", { text: `(${rewardsText})`, cls: "lg-reward-text" });
        }
        if (task.date || task.time) {
          const dateTimeText = `${task.date || ""} ${task.time || ""}`.trim();
          meta.createEl("span", { text: ` \u{1F4C5} ${dateTimeText}`, cls: "lg-date-text" });
        }
        if (task.skills.length > 0) {
          const skillsText = task.skills.map((s) => `#${s}`).join(" ");
          meta.createEl("span", { text: ` ${skillsText}`, cls: "lg-skill-tag" });
        }
      }
    });
  }
  renderStatsTab(parent) {
    const statsTab = parent.createEl("div", { cls: "lg-stats-tab" });
    statsTab.createEl("h3", { text: "\u{1F4CA} XP Statistics", cls: "lg-section-title" });
    const chartContainer = statsTab.createEl("div", { cls: "lg-chart-container" });
    const daysToShow = 14;
    const data = [];
    let maxDailyXp = 50;
    for (let i = daysToShow - 1; i >= 0; i--) {
      const date = /* @__PURE__ */ new Date();
      date.setDate(date.getDate() - i);
      const dateStr = formatDate(date);
      const dayLogs = this.plugin.settings.dailyXpLogs[dateStr] || {};
      let dailyTotal = 0;
      Object.values(dayLogs).forEach((val) => dailyTotal += val);
      data.push({
        label: i === 0 ? "Today" : date.getDate(),
        totalXp: dailyTotal,
        dateStr
      });
      maxDailyXp = Math.max(maxDailyXp, Math.abs(dailyTotal));
    }
    const chartBody = chartContainer.createEl("div", { cls: "lg-chart-body" });
    data.forEach((d) => {
      const barWrap = chartBody.createEl("div", { cls: "lg-bar-wrap" });
      const percent = Math.abs(d.totalXp) / maxDailyXp * 100;
      const bar = barWrap.createEl("div", {
        cls: `lg-bar ${d.totalXp >= 0 ? "is-positive" : "is-negative"}`,
        attr: { title: `${d.dateStr}: ${Math.round(d.totalXp * 10) / 10} XP` }
      });
      bar.style.height = `${Math.max(2, percent)}%`;
      barWrap.createEl("div", { text: d.label.toString(), cls: "lg-bar-label" });
    });
    statsTab.createEl("h3", { text: "\u{1F4CB} Recent History", cls: "lg-section-title" });
    this.renderStatistics(statsTab);
  }
  renderStatistics(parent) {
    const statsSection = parent.createEl("div", { cls: "lg-statistics-section" });
    statsSection.createEl("h3", { text: "\u{1F4CA} Daily Progress (Last 7 Days)", cls: "lg-section-title" });
    const statsGrid = statsSection.createEl("div", { cls: "lg-stats-grid-daily" });
    for (let i = 0; i < 7; i++) {
      const date = /* @__PURE__ */ new Date();
      date.setDate(date.getDate() - i);
      const dateStr = formatDate(date);
      const dayLogs = this.plugin.settings.dailyXpLogs[dateStr] || {};
      let dailyTotal = 0;
      Object.values(dayLogs).forEach((val) => dailyTotal += val);
      const dayCard = statsGrid.createEl("div", { cls: "lg-daily-stat-card" });
      const dayLabel = i === 0 ? "Today" : i === 1 ? "Yesterday" : dateStr;
      dayCard.createEl("div", { text: dayLabel, cls: "lg-daily-date" });
      const totalXp = Math.round(dailyTotal * 10) / 10;
      const xpText = dayCard.createEl("div", { text: `${totalXp > 0 ? "+" : ""}${totalXp} XP`, cls: "lg-daily-xp" });
      if (totalXp > 0) {
        xpText.addClass("xp-positive");
      } else if (totalXp < 0) {
        xpText.addClass("xp-negative");
      }
      if (Object.keys(dayLogs).length > 0) {
        const details = dayCard.createEl("div", { cls: "lg-daily-details" });
        Object.entries(dayLogs).forEach(([id, amount]) => {
          if (Math.abs(amount) < 0.1)
            return;
          const stat = this.plugin.settings.stats.find((s) => s.id === id) || this.plugin.settings.skills.find((s) => s.id === id || s.name === id);
          const name = stat ? stat.name : id;
          const roundedAmount = Math.round(amount * 10) / 10;
          details.createEl("div", { text: `${name}: ${roundedAmount > 0 ? "+" : ""}${roundedAmount}`, cls: "lg-daily-stat-item" });
        });
      }
    }
  }
  async handleTaskToggle(task, completed) {
    if (task.isProcessed)
      return;
    const file = this.app.vault.getAbstractFileByPath(this.plugin.settings.taskFilePath);
    if (!(file instanceof import_obsidian.TFile))
      return;
    this.plugin.isInternalChange = true;
    try {
      const oldTotalXp = getTotalXp(this.plugin.settings.stats);
      const currentTitle = getCurrentTitle(oldTotalXp, this.plugin.settings.titles);
      const taskId = getTaskKey(task);
      const now = /* @__PURE__ */ new Date();
      const penaltyInfo = this.plugin.getPenaltyInfo(task, now);
      let rewardString = "";
      if (completed) {
        const coins = this.plugin.applyReward(task, penaltyInfo);
        task.earnedCoins = coins;
        this.plugin.settings.completedTasks.push(taskId);
        rewardString = this.plugin.getRewardString(task, coins);
        const rewardsList = task.rewards.map((r) => {
          const stat = this.plugin.settings.stats.find((s) => s.id === r.statId);
          const finalAmount = r.earnedAmount || 0;
          return `${finalAmount > 0 ? "+" : ""}${finalAmount} ${stat ? stat.name : r.statId}`;
        }).join(", ");
        let rewardMsg = rewardsList ? ` (${rewardsList})` : "";
        rewardMsg += ` +\u{1F4B0} ${coins} coin`;
        if (penaltyInfo.isLate) {
          const reductionPercent = Math.round((1 - penaltyInfo.multiplier) * 100);
          const statusMsg = penaltyInfo.multiplier < 0 ? `${-Math.round(penaltyInfo.multiplier * 100)}% points deducted` : `${reductionPercent}% points reduced`;
          new import_obsidian.Notice(`\u26A0\uFE0F Completed Late: ${task.text}${rewardMsg}
${statusMsg} due to delay of ${penaltyInfo.minutesLate} minutes.`, 5e3);
          const aiPrompt = `I finished the task: "${task.text}". Rewards: ${rewardMsg}. Note: It was LATE by ${penaltyInfo.minutesLate} minutes, so I received a penalty: ${statusMsg}.`;
          await this.plugin.triggerAiAnalysis(aiPrompt);
        } else {
          new import_obsidian.Notice(`\u2705 Mission Accomplished: ${task.text}${rewardMsg}`);
          const aiPrompt = `I just finished the mission: "${task.text}"! I earned: ${rewardMsg}. I'm feeling productive!`;
          await this.plugin.triggerAiAnalysis(aiPrompt);
        }
        this.update();
      } else {
        this.plugin.applyUnreward(task);
        const index = this.plugin.settings.completedTasks.indexOf(taskId);
        if (index > -1) {
          this.plugin.settings.completedTasks.splice(index, 1);
        }
      }
      const content = await this.app.vault.read(file);
      const newContent = updateTaskInContent(content, task.originalLine, completed, completed, rewardString);
      await this.app.vault.modify(file, newContent);
      this.plugin.lastKnownContent = newContent;
      await this.plugin.saveSettings();
      const newTotalXp = getTotalXp(this.plugin.settings.stats);
      const newTitle = getCurrentTitle(newTotalXp, this.plugin.settings.titles);
      if (completed && newTitle.name !== currentTitle.name) {
        new import_obsidian.Notice(`\u{1F389} CONGRATULATIONS! \u{1F389}
You have reached a new title: ${newTitle.name}!`, 5e3);
        await this.plugin.saveSettings();
      }
    } finally {
      this.plugin.isInternalChange = false;
    }
  }
};

// src/ai.ts
var import_obsidian2 = require("obsidian");
var AIService = class {
  static async generateResponse(settings, context) {
    const { provider, apiKey, model } = settings.ai;
    if (!apiKey)
      return "API Key is missing. Please check settings.";
    try {
      if (provider === "openai") {
        return await this.callOpenAI(apiKey, model, context);
      } else if (provider === "gemini") {
        return await this.callGemini(apiKey, model, context);
      } else if (provider === "openrouter") {
        return await this.callOpenRouter(apiKey, model, context);
      }
      return "Unsupported provider.";
    } catch (e) {
      console.error("Life Gauge AI Error:", e);
      return `Error: ${e.message || "Failed to connect to AI"}`;
    }
  }
  static async callOpenAI(apiKey, model, context) {
    const response = await (0, import_obsidian2.requestUrl)({
      url: "https://api.openai.com/v1/chat/completions",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: model || "gpt-3.5-turbo",
        messages: [{ role: "user", content: context }],
        max_tokens: 50
      })
    });
    return response.json.choices[0].message.content;
  }
  static async callGemini(apiKey, model, context) {
    const response = await (0, import_obsidian2.requestUrl)({
      url: `https://generativelanguage.googleapis.com/v1beta/models/${model || "gemini-pro"}:generateContent?key=${apiKey}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: context }] }],
        generationConfig: {
          maxOutputTokens: 50
        }
      })
    });
    return response.json.candidates[0].content.parts[0].text;
  }
  static async callOpenRouter(apiKey, model, context) {
    const response = await (0, import_obsidian2.requestUrl)({
      url: "https://openrouter.ai/api/v1/chat/completions",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://obsidian.md",
        "X-Title": "Life-Gauge"
      },
      body: JSON.stringify({
        model: model || "openai/gpt-3.5-turbo",
        messages: [{ role: "user", content: context }],
        max_tokens: 50
      })
    });
    return response.json.choices[0].message.content;
  }
};

// main.ts
var LifeGaugePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "isInternalChange", false);
    __publicField(this, "isSyncing", false);
    __publicField(this, "pendingSync", false);
    __publicField(this, "lastKnownContent", "");
    __publicField(this, "AI_BEHAVIORS", [
      "Review: Thorough analysis of my productivity.",
      "Compare: Compare me to yesterday or goals.",
      "Complain: Complain about me neglecting my duties or letting the food run out.",
      "Sadness: Feeling disappointed if I underperform.",
      "Encouragement: Inspire and motivate strongly.",
      "Crazy: Humorously teasing about my habits.",
      "Anxious: Shows anxiety if I have a lot of overdue tasks.",
      "Excited: Shout with excitement when I achieve new achievements.",
      "Philosophy: Deep reflections on discipline and life.",
      "Curious: Ask about what I'm working on."
    ]);
  }
  async onload() {
    await this.loadSettings();
    this.updateHunger();
    await this.saveSettings();
    this.registerView(
      VIEW_TYPE_LIFE_GAUGE,
      (leaf) => new LifeGaugeView(leaf, this)
    );
    this.addRibbonIcon("gamepad", "Open Life Gauge", () => {
      this.activateView();
    });
    this.addSettingTab(new LifeGaugeSettingTab(this.app, this));
    this.registerInterval(
      window.setInterval(async () => {
        this.updateHunger();
        if (this.settings.ai.enabled) {
          const now = Date.now();
          const intervalMs = this.settings.ai.interval * 60 * 1e3;
          if (now - this.settings.lastAiTriggerTime >= intervalMs) {
            await this.triggerAiAnalysis("It's been a while! How are things going?");
          }
        }
        this.saveSettings();
      }, 60 * 1e3)
      // Every minute
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (this.isInternalChange)
          return;
        if (file instanceof import_obsidian3.TFile && file.path === this.settings.taskFilePath) {
          await this.syncTasksFromFile(file);
        }
      })
    );
  }
  applyReward(task, penaltyInfo) {
    const hungerMultiplier = this.getHungerMultiplier();
    const finalMultiplier = penaltyInfo.multiplier * hungerMultiplier;
    let totalXpAwarded = 0;
    task.rewards.forEach((reward) => {
      const stat = this.settings.stats.find((s) => s.id === reward.statId);
      if (stat) {
        const { requiredXp } = calculateLevel(stat.currentXp, stat.baseXp, stat.xpIncrement);
        const baseXP = Math.floor(Math.random() * 15) + 1;
        const bonusXP = (requiredXp - 100) / 10;
        const finalReward = (baseXP + bonusXP) * finalMultiplier;
        stat.currentXp += finalReward;
        totalXpAwarded += finalReward;
        reward.earnedAmount = Math.round(finalReward * 10) / 10;
        if (stat.currentXp < 0)
          stat.currentXp = 0;
      }
    });
    task.skills.forEach((skillName) => {
      const skill = this.settings.skills.find((s) => s.name.toLowerCase() === skillName || s.id.toLowerCase() === skillName);
      if (skill) {
        const { requiredXp } = calculateLevel(skill.currentXp, skill.baseXp, skill.xpIncrement);
        const baseXP = Math.floor(Math.random() * 15) + 1;
        const bonusXP = (requiredXp - 100) / 10;
        const finalReward = (baseXP + bonusXP) * finalMultiplier;
        skill.currentXp += finalReward;
        if (skill.currentXp < 0)
          skill.currentXp = 0;
      }
    });
    const coins = this.getCoinReward();
    this.settings.coins += coins;
    task.rewards.forEach((r) => {
      if (r.earnedAmount)
        this.logXp(r.statId, r.earnedAmount);
    });
    return coins;
  }
  logXp(id, amount) {
    const dateStr = formatDate(/* @__PURE__ */ new Date());
    if (!this.settings.dailyXpLogs[dateStr]) {
      this.settings.dailyXpLogs[dateStr] = {};
    }
    if (!this.settings.dailyXpLogs[dateStr][id]) {
      this.settings.dailyXpLogs[dateStr][id] = 0;
    }
    this.settings.dailyXpLogs[dateStr][id] += amount;
  }
  getHungerMultiplier() {
    if (this.settings.hunger >= this.settings.maxHunger)
      return 1.2;
    if (this.settings.hunger >= 70)
      return 1;
    if (this.settings.hunger >= 30) {
      return Math.max(0.1, this.settings.hunger / 100);
    }
    return 0.1;
  }
  getCoinReward() {
    const r = Math.random() * 100;
    if (r < 80)
      return Math.floor(Math.random() * 10) + 1;
    if (r < 90)
      return Math.floor(Math.random() * 10) + 11;
    if (r < 95)
      return Math.floor(Math.random() * 10) + 21;
    if (r < 98)
      return Math.floor(Math.random() * 10) + 31;
    return Math.floor(Math.random() * 10) + 41;
  }
  updateHunger() {
    const now = Date.now();
    const elapsedMinutes = (now - this.settings.lastHungerUpdate) / (1e3 * 60);
    if (elapsedMinutes <= 0)
      return;
    const depletionRate = this.settings.maxHunger / 100 * (1 / 30) * this.settings.penaltyPoint;
    const hungerLost = elapsedMinutes * depletionRate;
    this.settings.hunger = Math.max(0, this.settings.hunger - hungerLost);
    this.settings.lastHungerUpdate = now;
    const threshold = this.settings.maxHunger * 0.3;
    if (this.settings.hunger < threshold) {
      const intervalsElapsed = elapsedMinutes / 30;
      const xpLoss = intervalsElapsed * this.settings.penaltyPoint * (threshold - this.settings.hunger) / 4;
      this.settings.stats.forEach((stat) => {
        stat.currentXp = Math.max(0, stat.currentXp - xpLoss);
        this.logXp(stat.id, -xpLoss);
      });
      this.settings.skills.forEach((skill) => {
        skill.currentXp = Math.max(0, skill.currentXp - xpLoss);
        this.logXp(skill.id, -xpLoss);
      });
    }
  }
  applyUnreward(task) {
    task.rewards.forEach((reward) => {
      const stat = this.settings.stats.find((s) => s.id === reward.statId);
      if (stat) {
        stat.currentXp = Math.max(0, stat.currentXp - reward.amount);
        this.logXp(stat.id, -reward.amount);
      }
    });
    task.skills.forEach((skillName) => {
      const skill = this.settings.skills.find((s) => s.name.toLowerCase() === skillName || s.id.toLowerCase() === skillName);
      if (skill) {
        const totalReward = task.rewards.reduce((sum, r) => sum + r.amount, 0) || 10;
        skill.currentXp = Math.max(0, skill.currentXp - totalReward);
        this.logXp(skill.id, -totalReward);
      }
    });
  }
  getRewardString(task, coins) {
    const rewardsList = task.rewards.map((r) => {
      const stat = this.settings.stats.find((s) => s.id === r.statId);
      const finalAmount = r.earnedAmount || 0;
      return `${finalAmount > 0 ? "+" : ""}${finalAmount} ${stat ? stat.name : r.statId}`;
    }).join(" ");
    return `${rewardsList} +\u{1F4B0} ${coins} coin`.trim();
  }
  showRewardNotice(task, penaltyInfo) {
    const rewardsList = task.rewards.map((r) => {
      const stat = this.settings.stats.find((s) => s.id === r.statId);
      const finalAmount = r.earnedAmount || 0;
      return `${finalAmount > 0 ? "+" : ""}${finalAmount} ${stat ? stat.name : r.statId}`;
    }).join(", ");
    let rewardMsg = rewardsList ? ` (${rewardsList})` : "";
    if (task.earnedCoins) {
      rewardMsg += ` +\u{1F4B0} ${task.earnedCoins} coin`;
    }
    if (penaltyInfo.isLate) {
      const reductionPercent = Math.round((1 - penaltyInfo.multiplier) * 100);
      const statusMsg = penaltyInfo.multiplier < 0 ? `${-Math.round(penaltyInfo.multiplier * 100)}% points deducted` : `${reductionPercent}% points reduced`;
      new import_obsidian3.Notice(`\u26A0\uFE0F Completed Late: ${task.text}${rewardMsg}
${statusMsg} due to delay of ${penaltyInfo.minutesLate} minutes.`, 5e3);
    } else {
      new import_obsidian3.Notice(`\u2705 Mission Accomplished: ${task.text}${rewardMsg}`);
    }
  }
  async syncTasksFromFile(file) {
    if (this.isSyncing) {
      this.pendingSync = true;
      return;
    }
    this.isSyncing = true;
    try {
      const content = await this.app.vault.read(file);
      if (content === this.lastKnownContent)
        return;
      const oldTasks = this.lastKnownContent ? parseTasks(this.lastKnownContent, this.settings.stats) : [];
      const newTasks = parseTasks(content, this.settings.stats);
      const now = /* @__PURE__ */ new Date();
      let changed = false;
      let fileContentChanged = false;
      let currentContent = content;
      const newlyCompleted = newTasks.filter((t) => t.completed && !t.isProcessed);
      for (const task of newlyCompleted) {
        const key = getTaskKey(task);
        let rewardString = "";
        if (!this.settings.completedTasks.includes(key)) {
          const penaltyInfo = this.getPenaltyInfo(task, now);
          const oldTotalXp = this.settings.stats.reduce((acc, s) => acc + s.currentXp, 0);
          const oldTitle = getCurrentTitle(oldTotalXp, this.settings.titles);
          const coins = this.applyReward(task, penaltyInfo);
          task.earnedCoins = coins;
          this.settings.completedTasks.push(key);
          this.showRewardNotice(task, penaltyInfo);
          rewardString = this.getRewardString(task, coins);
          const newTotalXp = this.settings.stats.reduce((acc, s) => acc + s.currentXp, 0);
          const newTitle = getCurrentTitle(newTotalXp, this.settings.titles);
          if (newTitle.name !== oldTitle.name) {
            new import_obsidian3.Notice(`\u{1F389} CONGRATULATIONS! \u{1F389}
You have reached a new title: ${newTitle.name}!`, 5e3);
          }
          changed = true;
          if (this.settings.ai.enabled) {
            await this.triggerAiAnalysis(`I just completed a task: ${task.text}. I earned ${rewardString}.`);
          }
        }
        currentContent = updateTaskInContent(currentContent, task.originalLine, true, true, rewardString);
        fileContentChanged = true;
      }
      const unprocessedOld = oldTasks.filter((t) => t.completed && !t.isProcessed);
      for (const oldTask of unprocessedOld) {
        const stillChecked = newTasks.some((nt) => nt.originalLine === oldTask.originalLine && nt.completed);
        if (!stillChecked) {
          const key = getTaskKey(oldTask);
          if (this.settings.completedTasks.includes(key)) {
            this.applyUnreward(oldTask);
            const idx = this.settings.completedTasks.indexOf(key);
            if (idx > -1)
              this.settings.completedTasks.splice(idx, 1);
            changed = true;
          }
        }
      }
      if (fileContentChanged && currentContent !== content) {
        this.isInternalChange = true;
        await this.app.vault.modify(file, currentContent);
        this.lastKnownContent = currentContent;
        this.isInternalChange = false;
      } else {
        this.lastKnownContent = content;
      }
      if (changed) {
        await this.saveSettings();
      } else {
        this.refreshViews();
      }
      if (changed) {
        const totalXp = this.settings.stats.reduce((acc, s) => acc + s.currentXp, 0);
      }
    } finally {
      this.isSyncing = false;
      if (this.pendingSync) {
        this.pendingSync = false;
        const file2 = this.app.vault.getAbstractFileByPath(this.settings.taskFilePath);
        if (file2 instanceof import_obsidian3.TFile) {
          await this.syncTasksFromFile(file2);
        }
      }
    }
  }
  getPenaltyInfo(task, now) {
    if (!task.date && !task.time)
      return { multiplier: 1, isLate: false, minutesLate: 0 };
    let deadline;
    if (task.date && task.time) {
      deadline = /* @__PURE__ */ new Date(`${task.date}T${task.time}`);
    } else if (task.date) {
      deadline = /* @__PURE__ */ new Date(`${task.date}T23:59:59`);
    } else {
      const today = now.toISOString().split("T")[0];
      deadline = /* @__PURE__ */ new Date(`${today}T${task.time}`);
    }
    if (now <= deadline)
      return { multiplier: 1, isLate: false, minutesLate: 0 };
    const minutesLate = Math.floor((now.getTime() - deadline.getTime()) / (1e3 * 60));
    const multiplier = 1 - minutesLate * this.settings.penaltyPoint / 100;
    return { multiplier, isLate: true, minutesLate };
  }
  async triggerAiAnalysis(triggerPrompt) {
    if (!this.settings.ai.enabled || !this.settings.ai.apiKey)
      return;
    const totalXp = this.settings.stats.reduce((acc, s) => acc + s.currentXp, 0);
    const title = getCurrentTitle(totalXp, this.settings.titles);
    const behaviorIdx = Math.floor(Math.random() * this.AI_BEHAVIORS.length);
    const currentBehavior = this.AI_BEHAVIORS[behaviorIdx];
    const statsInfo = this.settings.stats.map((s) => {
      const { level, progress } = calculateLevel(s.currentXp, s.baseXp, s.xpIncrement);
      return `- ${s.name} (${s.id}): Level ${level} (${Math.floor(progress)}%)`;
    }).join("\n");
    const context = `
You are ${this.settings.ai.name}, a helpful and cheeky companion. Keep your response EXTREMELY SHORT (1-2 sentences, max 20 words).
Current Status:
- Satiety (Hunger): ${Math.floor(this.settings.hunger)}/${this.settings.maxHunger}
- Current Rank: ${title.name}
- Total Coins: ${this.settings.coins}
- Trigger Context: ${triggerPrompt}
- Primary Behavioral Trait for this response: ${currentBehavior}

Current Player Stats:
${statsInfo}

Personality Guidelines based on Stats:
1. If "Strength" (STR) is high (Level 5+), be confident, bold, and energetic.
2. If "Knowledge/Intelligence" (INT) is low (Level 1-2), be slightly confused, silly, or include a "goofy action" or a "dumb mistake" in your speech.
3. If "Vitality" (VIT) is high, be overly healthy and enthusiastic about physical well-being.
4. If "Dexterity" (DEX) is low, mention being clumsy or dropping something.
5. If Satiety is low, act hungry or weak regardless of other stats.

Rules:
1. Speak as ${this.settings.ai.name}. Be brief (max 2 sentences).
2. Based on the rules above, react to the user current status and the trigger context.
3. Blend the "Primary Behavioral Trait" with the "Personality Guidelines" above.
4. Output ONLY the speech of the character.
`;
    const response = await AIService.generateResponse(this.settings, context);
    this.settings.lastAiResponse = response;
    this.settings.ai.newResponse = true;
    this.settings.lastAiTriggerTime = Date.now();
    this.saveSettings();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    const file = this.app.vault.getAbstractFileByPath(this.settings.taskFilePath);
    if (file instanceof import_obsidian3.TFile) {
      this.lastKnownContent = await this.app.vault.read(file);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshViews();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_LIFE_GAUGE)[0];
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({
        type: VIEW_TYPE_LIFE_GAUGE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_LIFE_GAUGE).forEach((leaf) => {
      if (leaf.view instanceof LifeGaugeView) {
        leaf.view.update();
      }
    });
  }
  showAddRewardModal() {
    new AddRewardModal(this.app, this).open();
  }
};
var AddRewardModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    __publicField(this, "plugin");
    __publicField(this, "name", "New Reward");
    __publicField(this, "icon", "\u{1F381}");
    __publicField(this, "description", "");
    __publicField(this, "cost", 50);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add Custom Reward" });
    new import_obsidian3.Setting(contentEl).setName("Reward Name").addText(
      (text) => text.setValue(this.name).onChange((value) => {
        this.name = value;
      })
    );
    new import_obsidian3.Setting(contentEl).setName("Icon").addText(
      (text) => text.setValue(this.icon).onChange((value) => {
        this.icon = value || "\u{1F381}";
      })
    );
    new import_obsidian3.Setting(contentEl).setName("Description").addText(
      (text) => text.setValue(this.description).onChange((value) => {
        this.description = value;
      })
    );
    new import_obsidian3.Setting(contentEl).setName("Cost (Coins)").addText(
      (text) => text.setValue(this.cost.toString()).onChange((value) => {
        const val = parseInt(value);
        if (!isNaN(val))
          this.cost = val;
      })
    );
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Add to Shop").setCta().onClick(async () => {
        this.plugin.settings.customShopItems.push({
          id: `item-${Date.now()}`,
          name: this.name,
          icon: this.icon,
          description: this.description,
          cost: this.cost
        });
        await this.plugin.saveSettings();
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var LifeGaugeSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Life Gauge Settings" });
    containerEl.createEl("h3", { text: "\u{1F916} AI Companion (Mascot)" });
    new import_obsidian3.Setting(containerEl).setName("Enable AI Companion").setDesc("Turn on your AI companion. This will replace the Title system in the header.").addToggle((toggle) => toggle.setValue(this.plugin.settings.ai.enabled).onChange(async (value) => {
      this.plugin.settings.ai.enabled = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.ai.enabled) {
      new import_obsidian3.Setting(containerEl).setName("Companion Name").setDesc("How should your companion be called? (e.g. Paimon)").addText((text) => text.setValue(this.plugin.settings.ai.name).onChange(async (value) => {
        this.plugin.settings.ai.name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(containerEl).setName("AI Provider").addDropdown((dropdown) => dropdown.addOption("openai", "OpenAI").addOption("gemini", "Google Gemini").addOption("openrouter", "OpenRouter").setValue(this.plugin.settings.ai.provider).onChange(async (value) => {
        this.plugin.settings.ai.provider = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(containerEl).setName("API Key").addText((text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.ai.apiKey).onChange(async (value) => {
        this.plugin.settings.ai.apiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(containerEl).setName("Model").setDesc("e.g. gpt-3.5-turbo, gemini-pro, etc.").addText((text) => text.setValue(this.plugin.settings.ai.model).onChange(async (value) => {
        this.plugin.settings.ai.model = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(containerEl).setName("Trigger Interval (Minutes)").setDesc("How often should the AI speak to you automatically?").addSlider((slider) => slider.setLimits(5, 720, 5).setValue(this.plugin.settings.ai.interval).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.ai.interval = value;
        await this.plugin.saveSettings();
      }));
    }
    containerEl.createEl("h3", { text: "\u{1F4C1} Task Configuration" });
    new import_obsidian3.Setting(containerEl).setName("Avatar Path").setDesc("Path to your avatar image in the vault.").addText((text) => text.setValue(this.plugin.settings.avatarPath).onChange(async (value) => {
      this.plugin.settings.avatarPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Task File Path").setDesc("Path to the Markdown file containing your tasks.").addText((text) => text.setValue(this.plugin.settings.taskFilePath).onChange(async (value) => {
      this.plugin.settings.taskFilePath = value;
      const file = this.app.vault.getAbstractFileByPath(value);
      if (file instanceof import_obsidian3.TFile) {
        this.plugin.lastKnownContent = await this.app.vault.read(file);
      } else {
        this.plugin.lastKnownContent = "";
      }
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u{1F480} Penalty Configuration" });
    new import_obsidian3.Setting(containerEl).setName("Penalty Multiplier (Penalty Point)").setDesc("Multiplier for all penalties. Higher values result in more XP lost for late tasks and hunger. \nFormula for late tasks: Points - (Min Late * Points / 100) * PenaltyPoint. \nFormula for hunger (per 30m): PenaltyPoint * (MaxSatiety * 0.3 - Satiety) / 4.").addText((text) => text.setPlaceholder("1").setValue(this.plugin.settings.penaltyPoint.toString()).onChange(async (value) => {
      const val = parseFloat(value);
      if (!isNaN(val)) {
        this.plugin.settings.penaltyPoint = val;
        await this.plugin.saveSettings();
      }
    }));
    const statsDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const statsSummary = statsDetails.createEl("summary");
    statsSummary.createEl("h3", { text: "Stats Configuration", cls: "lg-settings-summary-title" });
    this.plugin.settings.stats.forEach((stat, index) => {
      const statHeader = statsDetails.createEl("div", { cls: "lg-setting-stat-header" });
      statHeader.style.display = "flex";
      statHeader.style.justifyContent = "space-between";
      statHeader.style.alignItems = "center";
      const titleEl = statHeader.createEl("h4", { text: stat.name });
      titleEl.style.margin = "0";
      const deleteBtn = statHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.stats.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian3.Setting(statsDetails).setName("Stat Name").addText((text) => text.setValue(stat.name).onChange(async (value) => {
        this.plugin.settings.stats[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(statsDetails).setName("Stat Icon").addText((text) => text.setValue(stat.icon).onChange(async (value) => {
        this.plugin.settings.stats[index].icon = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(statsDetails).setName(`${stat.name} Color`).setDesc(`Color for the ${stat.name} progress bar.`).addColorPicker((color) => color.setValue(stat.color).onChange(async (value) => {
        this.plugin.settings.stats[index].color = value;
        await this.plugin.saveSettings();
      }));
      statsDetails.createEl("hr");
    });
    new import_obsidian3.Setting(statsDetails).setName("Add New Stat").setDesc("Create a new attribute to track.").addButton((btn) => btn.setButtonText("Add Stat").onClick(async () => {
      this.plugin.settings.stats.push({
        id: `stat-${Date.now()}`,
        name: "New Stat",
        icon: "\u2B50",
        currentXp: 0,
        level: 1,
        color: "#cccccc",
        baseXp: 100,
        xpIncrement: 50
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    const skillsDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const skillsSummary = skillsDetails.createEl("summary");
    skillsSummary.createEl("h3", { text: "Skills Configuration", cls: "lg-settings-summary-title" });
    this.plugin.settings.skills.forEach((skill, index) => {
      const skillHeader = skillsDetails.createEl("div", { cls: "lg-setting-stat-header" });
      skillHeader.style.display = "flex";
      skillHeader.style.justifyContent = "space-between";
      skillHeader.style.alignItems = "center";
      const titleEl = skillHeader.createEl("h4", { text: skill.name });
      titleEl.style.margin = "0";
      const deleteBtn = skillHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.skills.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian3.Setting(skillsDetails).setName("Skill Name").addText((text) => text.setValue(skill.name).onChange(async (value) => {
        this.plugin.settings.skills[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(skillsDetails).setName("Skill Icon").addText((text) => text.setValue(skill.icon).onChange(async (value) => {
        this.plugin.settings.skills[index].icon = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(skillsDetails).setName(`${skill.name} Color`).addColorPicker((color) => color.setValue(skill.color).onChange(async (value) => {
        this.plugin.settings.skills[index].color = value;
        await this.plugin.saveSettings();
      }));
      skillsDetails.createEl("hr");
    });
    new import_obsidian3.Setting(skillsDetails).setName("Create New Skill").setDesc("Skills track your real-world progress (e.g., English, Java).").addButton((btn) => btn.setButtonText("Add Skill").onClick(async () => {
      this.plugin.settings.skills.push({
        id: `skill-${Date.now()}`,
        name: "New Skill",
        icon: "\u{1F3AF}",
        currentXp: 0,
        level: 1,
        color: "#8e44ad",
        baseXp: 100,
        xpIncrement: 50
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    const titlesDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const titlesSummary = titlesDetails.createEl("summary");
    titlesSummary.createEl("h3", { text: "\u{1F3C6} Titles configuration", cls: "lg-settings-summary-title" });
    this.plugin.settings.titles.forEach((title, index) => {
      const titleHeader = titlesDetails.createEl("div", { cls: "lg-setting-stat-header" });
      titleHeader.style.display = "flex";
      titleHeader.style.justifyContent = "space-between";
      titleHeader.style.alignItems = "center";
      const titleLabel = titleHeader.createEl("h4", { text: title.name });
      titleLabel.style.margin = "0";
      const deleteBtn = titleHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.titles.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian3.Setting(titlesDetails).setName("Title Name").addText((text) => text.setValue(title.name).onChange(async (value) => {
        this.plugin.settings.titles[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(titlesDetails).setName("Icon").addText((text) => text.setValue(title.icon).onChange(async (value) => {
        this.plugin.settings.titles[index].icon = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(titlesDetails).setName("XP Threshold").setDesc("The amount of XP required to receive this title.").addText((text) => text.setValue(title.threshold.toString()).onChange(async (value) => {
        const val = parseInt(value);
        if (!isNaN(val)) {
          this.plugin.settings.titles[index].threshold = val;
          await this.plugin.saveSettings();
        }
      }));
      new import_obsidian3.Setting(titlesDetails).setName("Description").addTextArea((text) => text.setValue(title.description).onChange(async (value) => {
        this.plugin.settings.titles[index].description = value;
        await this.plugin.saveSettings();
      }));
      titlesDetails.createEl("hr");
    });
    new import_obsidian3.Setting(titlesDetails).setName("Add New Title").addButton((btn) => btn.setButtonText("Add Title").onClick(async () => {
      this.plugin.settings.titles.push({
        threshold: 0,
        name: "New Title",
        icon: "\u{1F195}",
        description: "Description for this title..."
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    const customShopItemsDetails = containerEl.createEl("details", { cls: "lg-settings-details" });
    const customShopItemsSummary = customShopItemsDetails.createEl("summary");
    customShopItemsSummary.createEl("h3", { text: "\u{1F381} Custom Reward Shop", cls: "lg-settings-summary-title" });
    this.plugin.settings.customShopItems.forEach((item, index) => {
      const itemHeader = customShopItemsDetails.createEl("div", { cls: "lg-setting-stat-header" });
      itemHeader.style.display = "flex";
      itemHeader.style.justifyContent = "space-between";
      itemHeader.style.alignItems = "center";
      const itemTitle = itemHeader.createEl("h4", { text: item.name });
      itemTitle.style.margin = "0";
      const deleteBtn = itemHeader.createEl("button", { text: "Delete", cls: "mod-warning" });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.customShopItems.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
      new import_obsidian3.Setting(customShopItemsDetails).setName("Item Name").addText((text) => text.setValue(item.name).onChange(async (value) => {
        this.plugin.settings.customShopItems[index].name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(customShopItemsDetails).setName("Icon").addText((text) => text.setValue(item.icon).setPlaceholder("\u{1F381}").onChange(async (value) => {
        this.plugin.settings.customShopItems[index].icon = value || "\u{1F381}";
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(customShopItemsDetails).setName("Description").addText((text) => text.setValue(item.description).onChange(async (value) => {
        this.plugin.settings.customShopItems[index].description = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(customShopItemsDetails).setName("Cost (Coins)").addText((text) => text.setValue(item.cost.toString()).onChange(async (value) => {
        const val = parseInt(value);
        if (!isNaN(val)) {
          this.plugin.settings.customShopItems[index].cost = val;
          await this.plugin.saveSettings();
        }
      }));
      customShopItemsDetails.createEl("hr");
    });
    new import_obsidian3.Setting(customShopItemsDetails).setName("Add New Item").addButton((btn) => btn.setButtonText("Add Item").onClick(async () => {
      this.plugin.settings.customShopItems.push({
        id: `item-${Date.now()}`,
        name: "New Reward",
        icon: "\u{1F381}",
        description: "Reward description...",
        cost: 50
      });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
};
